USE [DBAdmin]
GO

/****** Object:  StoredProcedure [scs].[scs_AG_SECONDARY_CREATE]    Script Date: 12/15/2017 9:45:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [scs].[scs_AG_SECONDARY_CREATE]
@AGNAME SYSNAME,
@database SYSNAME = NULL, 
@scs_EXECUTE CHAR(1) = 'N'
AS
BEGIN
DECLARE @SECONDARYCODE NVARCHAR(MAX)

IF NOT EXISTS (SELECT AG_name FROM DBADMIN.scs.scs_vw_AGInfo WHERE AG_NAME = @AGNAME) 
BEGIN
SET @SECONDARYCODE =  'USE MASTER 
ALTER AVAILABILITY GROUP [' + @AGName +'] JOIN'
END



IF @database IS NOT NULL OR (EXISTS(SELECT NAME FROM DBADMIN.scs.scs_vw_VU_User_DBs WHERE NAME = @database))
BEGIN
IF @SECONDARYCODE IS NULL 
BEGIN 
SET @SECONDARYCODE = 'USE MASTER'
END

SET @SECONDARYCODE = @SECONDARYCODE + '

ALTER DATABASE [' + @DATABASE + '] SET HADR AVAILABILITY GROUP = [' + @AGNAME + ']; '
END

PRINT @SECONDARYCODE 
IF @scs_EXECUTE = 'Y'
BEGIN
EXEC (@SECONDARYCODE) 
END
END
GO

