USE [master]
GO

DECLARE @FileLocation NVARCHAR(250) = (SELECT LEFT(physical_name, LEN(physical_name)- 10) FROM sys.master_files WHERE name = 'master')
DECLARE @sql NVARCHAR(MAX)

/****** Object:  Database [DBAdmin]    Script Date: 4/5/2017 12:23:05 PM ******/
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'DBAdmin')
BEGIN
DROP DATABASE DBAdmin
END

/****** Object:  Database [DBAdmin]    Script Date: 8/16/2016 1:01:22 PM ******/
SET @sql = 'CREATE DATABASE [DBAdmin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N''DBAdmin'', FILENAME = ''' + @FileLocation + 'DBAdmin.mdf'' , SIZE = 154240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N''DBAdmin_log'', FILENAME = ''' + @FileLocation + 'DBAdmin_log.ldf'' , SIZE = 136064KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB)'

EXEC sys.sp_executesql @sql

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAdmin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBAdmin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBAdmin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBAdmin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBAdmin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBAdmin] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBAdmin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBAdmin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBAdmin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBAdmin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBAdmin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBAdmin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBAdmin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBAdmin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBAdmin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBAdmin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBAdmin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBAdmin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBAdmin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBAdmin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBAdmin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBAdmin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBAdmin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBAdmin] SET RECOVERY FULL
GO

ALTER DATABASE [DBAdmin] SET  MULTI_USER 
GO

ALTER DATABASE [DBAdmin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBAdmin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBAdmin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBAdmin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBAdmin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBAdmin] SET  READ_WRITE 
GO

USE [DBAdmin]
EXEC sp_changedbowner 'sa';  
